spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

jwt:
  secret-key: ${JWT_KEY}
  access-exp: ${JWT_ACCESS_EXP}
  refresh-exp: ${JWT_REFRESH_EXP}

infra:
  finance:
    redirect-uri: ${FINANCE_API_REDIRECT_URI}
    client-id: ${FINANCE_API_ID}
    client-secret: ${FINANCE_API_SECRET}
    use-organization-code: ${FINANCE_API_ORG_CODE}
  kakao:
    api-key: ${KAKAO_INFRA_KEY}